package sshconfig

import (
	"fmt"
	"sort"
	"strings"
)

var directiveOrder = []string{
	"HostName",
	"User",
	"Port",
	"IdentityFile",
	"IdentitiesOnly",
	"ProxyJump",
	"ProxyCommand",
	"ForwardAgent",
	"ServerAliveInterval",
	"ServerAliveCountMax",
	"AddKeysToAgent",
	"UseKeychain",
}

func Render(entries []Entry, activeProfiles []string) string {
	var out strings.Builder
	out.WriteString("# Generated by synk. Do not edit by hand.\n")
	if len(activeProfiles) > 0 {
		out.WriteString("# Active profiles: ")
		out.WriteString(strings.Join(normalizeProfiles(activeProfiles), " -> "))
		out.WriteString("\n")
	}
	out.WriteString("\n")

	for _, entry := range entries {
		writeEntryBlock(&out, entry)
		out.WriteString("\n")
	}

	return out.String()
}

func RenderEntryBlock(entry Entry) string {
	var out strings.Builder
	writeEntryBlock(&out, entry)
	return strings.TrimRight(out.String(), "\n")
}

func writeEntryBlock(out *strings.Builder, entry Entry) {
	out.WriteString(fmt.Sprintf("# Profile: %s", entry.Profile))
	if entry.Source != "" {
		out.WriteString(fmt.Sprintf(" | Source: %s", entry.Source))
	}
	out.WriteString("\n")
	out.WriteString("Host ")
	out.WriteString(entry.Host)
	out.WriteString("\n")
	for _, note := range commentLines(entry.Notes) {
		out.WriteString("    # ")
		out.WriteString(note)
		out.WriteString("\n")
	}

	for _, key := range orderedDirectiveKeys(entry.Directives) {
		value := strings.TrimSpace(entry.Directives[key])
		if value == "" {
			continue
		}
		out.WriteString("    ")
		out.WriteString(key)
		out.WriteString(" ")
		out.WriteString(value)
		out.WriteString("\n")
	}
}

func commentLines(notes string) []string {
	notes = strings.TrimSpace(notes)
	if notes == "" {
		return nil
	}

	lines := strings.Split(strings.ReplaceAll(notes, "\r\n", "\n"), "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "#")
		line = strings.TrimSpace(line)
		if line != "" {
			out = append(out, line)
		}
	}
	return out
}

func orderedDirectiveKeys(directives map[string]string) []string {
	if len(directives) == 0 {
		return nil
	}

	seen := map[string]bool{}
	keys := []string{}
	for _, key := range directiveOrder {
		if _, ok := directives[key]; ok {
			keys = append(keys, key)
			seen[key] = true
		}
	}

	rest := []string{}
	for key := range directives {
		if !seen[key] {
			rest = append(rest, key)
		}
	}
	sort.Strings(rest)
	keys = append(keys, rest...)
	return keys
}
