package sshconfig

import "testing"

func TestRenderOpenSSHConfig(t *testing.T) {
	rendered := Render([]Entry{
		{
			Host:    "github.com",
			Profile: "pro",
			Source:  "GitHub Pro",
			Notes:   "Use work key.\nDo not edit manually.",
			Directives: map[string]string{
				"IdentityFile": "~/.ssh/id_pro",
				"HostName":     "ssh.github.com",
				"User":         "git",
				"Port":         "443",
				"ProxyJump":    "bastion",
			},
		},
	}, []string{"general", "pro"})

	want := "# Generated by synk. Do not edit by hand.\n" +
		"# Active profiles: general -> pro\n\n" +
		"# Profile: pro | Source: GitHub Pro\n" +
		"Host github.com\n" +
		"    # Use work key.\n" +
		"    # Do not edit manually.\n" +
		"    HostName ssh.github.com\n" +
		"    User git\n" +
		"    Port 443\n" +
		"    IdentityFile ~/.ssh/id_pro\n" +
		"    ProxyJump bastion\n\n"
	if rendered != want {
		t.Fatalf("rendered:\n%s\nwant:\n%s", rendered, want)
	}
}
